# PLC Address Map
# 서보모터는 PLC 경유로 제어

[Write]
# PC -> PLC (명령)
SERVO_Rotate_1=E30001
SERVO_Rotate_2=E30002
SERVO_Rotate_3=E30003
SERVO_Rotate_4=E30004
SERVO_Rotate_5=E30005
SERVO_Home=E30006

[Read]
# PLC -> PC (응답/Ack)
SERVO_Rotate_1_Ack=E40001
SERVO_Rotate_2_Ack=E40002
SERVO_Rotate_3_Ack=E40003
SERVO_Rotate_4_Ack=E40004
SERVO_Rotate_5_Ack=E40005
SERVO_Home_Ack=E40006
